import { NextResponse } from "next/server";

import { callGas } from "../../../../lib/integrations/gasClient";
import { withApiLog } from "../../../../lib/obs/apiLog";
import { getOrCreateRequestId } from "../../../../lib/obs/requestId";

type BatchCreatePayload = {
  note?: string;
  meta?: Record<string, unknown>;
};

type BatchCreateResult = {
  replayed?: boolean;
  id: string;
  code: string;
  status: string;
  created_at: string;
};

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function validatePayload(body: unknown): { payload?: BatchCreatePayload; error?: string } {
  if (!isRecord(body)) {
    return { error: "Body must be a JSON object" };
  }

  if (body.code !== undefined) {
    return { error: "Field 'code' is not allowed; code is generated by the server" };
  }

  let noteVal: string | undefined;
  if (body.note !== undefined) {
    if (typeof body.note !== "string") {
      return { error: "Field 'note' must be a string when provided" };
    }
    noteVal = body.note;
  }

  let metaVal: Record<string, unknown> | undefined;
  if (body.meta !== undefined) {
    if (!isRecord(body.meta)) {
      return { error: "Field 'meta' must be an object when provided" };
    }
    metaVal = body.meta;
  }

  const payload: BatchCreatePayload = {
    ...(noteVal !== undefined ? { note: noteVal } : {}),
    ...(metaVal !== undefined ? { meta: metaVal } : {}),
  };

  return { payload };
}

export async function POST(request: Request) {
  const startedAt = Date.now();
  let requestId = getOrCreateRequestId(request);
  const path = new URL(request.url).pathname;
  const actor = "service";

  const finalize = (response: NextResponse, code?: string) =>
    withApiLog(response, {
      startedAt,
      requestId,
      method: request.method,
      path,
      actor,
      ...(code ? { code } : {}),
    });

  let body: unknown;

  try {
    body = await request.json();
  } catch {
    return finalize(NextResponse.json({ ok: false, error: "Invalid JSON body" }, { status: 400 }), "BAD_REQUEST");
  }

  if (isRecord(body) && typeof body.request_id === "string" && body.request_id.trim().length > 0) {
    requestId = body.request_id.trim();
  }

  const { payload, error } = validatePayload(body);
  if (!payload) {
    return finalize(NextResponse.json({ ok: false, error }, { status: 400 }), "BAD_REQUEST");
  }

  try {
    const gasResponse = await callGas<BatchCreateResult>("batch_create", payload, requestId);

    if (!gasResponse.ok || !gasResponse.data) {
      const rawErr: unknown = (gasResponse as unknown as { error?: unknown }).error;
      const errorMessage =
        typeof rawErr === "string"
          ? rawErr
          : rawErr
          ? JSON.stringify(rawErr)
          : "GAS batch_create failed";

      const lower = errorMessage.toLowerCase();
      const isLockOrTimeout =
        lower.includes("lock_conflict") ||
        lower.includes("lock timeout") ||
        lower.includes("timeout after") ||
        lower.includes("timed out");

      const status = isLockOrTimeout ? 503 : 502;
      return finalize(NextResponse.json({ ok: false, error: errorMessage }, { status }));
    }

    const replayed = gasResponse.data.replayed === true;
    const { replayed: _replayed, ...data } = gasResponse.data;
    const status = replayed ? 200 : 201;

    return finalize(NextResponse.json({ ok: true, data, replayed }, { status }));
  } catch (caughtError) {
    const message = caughtError instanceof Error ? caughtError.message : "Unknown error";
    return finalize(NextResponse.json({ ok: false, error: message }, { status: 500 }));
  }
}
